import = [ "~/.config/alacritty/afterglow.toml" ]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/local/bin/fish"

[font]
size = 12.0

[font.bold]
family = "BitstreamVeraSansMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BitstreamVeraSansMono Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "BitstreamVeraSansMono Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "BitstreamVeraSansMono Nerd Font Mono"
style = "Roman"

# alt+. for previous argument
[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

# Support ctrl+enter and shift+enter in terminal (vim)
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
