theme = "base16_tomorrow_dark"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[keys.normal]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"\\" = { "w" = ":w", "c" = ":config-open", "r" = ":config-reload" }
"]" = { "]" = ["goto_next_function", "align_view_top"] } # select next function and align to top
"[" = { "[" = ["goto_prev_function", "align_view_top"] } # select prev function and align to top
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # enter key move to start of next line
X = "extend_line_above"
D = "delete_char_backward"
"S-left" = "jump_view_left"
"S-right" = "jump_view_right"
"S-up" = "jump_view_up"
"S-down" = "jump_view_down"
"A-S-left" = "swap_view_left"
"A-S-right" = "swap_view_right"
"A-S-up" = "swap_view_up"
"A-S-down" = "swap_view_down"
